CREATE TABLE USER_COMMENTS (
    IDX NUMBER PRIMARY KEY,
    QUEST_IDX NUMBER NOT NULL, --REFERENCES QUESTIONS(IDX),
    USER_IDX NUMBER NOT NULL, --REFERENCES USERS(IDX),
    USER_COMMENT VARCHAR2(1000) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE
);