CREATE TABLE USERS ( 
    IDX NUMBER PRIMARY KEY,
    ID VARCHAR2(50) UNIQUE NOT NULL,
    PW VARCHAR2(255) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    GRADE VARCHAR2(20) NOT NULL,
    GENDER VARCHAR2(10),
    AGE NUMBER,
    REG_DATE DATE DEFAULT SYSDATE
);