CREATE TABLE USERS ( 
    IDX NUMBER PRIMARY KEY,
<<<<<<< HEAD
    ID VARCHAR2(50) UNIQUE NOT NULL,
    PW VARCHAR2(255) NOT NULL,
=======
    ID VARCHAR2(100) UNIQUE NOT NULL,
    PW VARCHAR2(200) NOT NULL,
>>>>>>> 71324c2 (UserDAO + User sql 대소문자 수정)
    NAME VARCHAR2(100) NOT NULL,
    GRADE VARCHAR2(20) NOT NULL,
    GENDER VARCHAR2(10),
    AGE NUMBER,
    REG_DATE DATE DEFAULT SYSDATE
);