CREATE TABLE QUESTIONS (
    IDX NUMBER PRIMARY KEY,
    TITLE VARCHAR2(255) NOT NULL,
    CONTENT_A VARCHAR2(255) NOT NULL,
    CONTENT_B VARCHAR2(255) NOT NULL,
    WRITER NUMBER NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE
);