CREATE TABLE USER_ANSWERS (
    IDX NUMBER PRIMARY KEY,
    USER_IDX NUMBER NOT NULL, -- REFERENCES USERS(IDX),
    QUEST_IDX NUMBER NOT NULL, -- REFERENCES QUESTIONS(IDX),
    CONTENT VARCHAR2(255) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE
);