CREATE TABLE USER_ANSWERS (
    IDX NUMBER PRIMARY KEY,
    USER_IDX NUMBER NOT NULL, -- REFERENCES USERS(IDX),
    QUEST_IDX NUMBER NOT NULL, -- REFERENCES QUESTIONS(IDX),
    CONTENT VARCHAR2(255) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE QUESTIONS (
    IDX NUMBER PRIMARY KEY,
    TITLE VARCHAR2(255) NOT NULL,
    CONTENT_A VARCHAR2(255) NOT NULL,
    CONTENT_B VARCHAR2(255) NOT NULL,
    WRITER NUMBER NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE USERS ( 
    IDX NUMBER PRIMARY KEY,
    ID VARCHAR2(50) UNIQUE NOT NULL,
    PW VARCHAR2(255) NOT NULL,

    NAME VARCHAR2(100) NOT NULL,
    GRADE VARCHAR2(20) NOT NULL,
    GENDER VARCHAR2(10),
    AGE NUMBER,
    REG_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE USER_COMMENTS (
    IDX NUMBER PRIMARY KEY,
    QUEST_IDX NUMBER NOT NULL, --REFERENCES QUESTIONS(IDX),
    USER_IDX NUMBER NOT NULL, --REFERENCES USERS(IDX),
    USER_COMMENT VARCHAR2(1000) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE
);
INSERT INTO USERS (IDX, ID, PW, NAME, GRADE, GENDER, AGE) VALUES (0,'admin','1234','어드민','admin','여',25); 
INSERT INTO USERS (IDX, ID, PW, NAME, GRADE, GENDER, AGE) VALUES (1,'user','1234','유저','user','여',25); 
select * from USERS where IDX=0;

drop table USERS;

