CREATE TABLE USER_ANSWERS (
    IDX NUMBER PRIMARY KEY,
    USER_IDX NUMBER NOT NULL, -- REFERENCES USERS(IDX),
    QUEST_IDX NUMBER NOT NULL, -- REFERENCES QUESTIONS(IDX),
    CONTENT VARCHAR2(255) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE QUESTIONS (
    IDX NUMBER PRIMARY KEY,
    TITLE VARCHAR2(255) NOT NULL,
    CONTENT_A VARCHAR2(255) NOT NULL,
    CONTENT_B VARCHAR2(255) NOT NULL,
    WRITER NUMBER NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE USERS ( 
    IDX NUMBER PRIMARY KEY,
<<<<<<< HEAD
    ID VARCHAR2(50) UNIQUE NOT NULL,
    PW VARCHAR2(255) NOT NULL,
=======
    ID VARCHAR2(100) UNIQUE NOT NULL,
    PW VARCHAR2(200) NOT NULL,
>>>>>>> 71324c2 (UserDAO + User sql 대소문자 수정)
    NAME VARCHAR2(100) NOT NULL,
    GRADE VARCHAR2(20) NOT NULL,
    GENDER VARCHAR2(10),
    AGE NUMBER,
    REG_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE USER_COMMENTS (
    IDX NUMBER PRIMARY KEY,
    QUEST_IDX NUMBER NOT NULL, --REFERENCES QUESTIONS(IDX),
    USER_IDX NUMBER NOT NULL, --REFERENCES USERS(IDX),
    USER_COMMENT VARCHAR2(1000) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE
);
